[SERVICES-2347] Token volume previous 24h
multiversx/mx-exchange-service pull request #1355
Opened 2024-05-27 06:28 UTC by mad2sm0key

## Reasoning
- token volume and previous 24h volume is needed for trending score computation

  
## Proposed Changes
- add `previous24hVolume` field and resolver
- add getHourlySumValues timescaledb query accepting custom interval parameters
- compute volume for the 2 time windows using a single timescaledb query for the past 2 days, and splitting the results afterwards
- create tokens cache warmer cron service

## How to test
## How to test
```
query {
  tokens(
    identifiers: ["HTM-f51d55"],
  ) {
    identifier
    volumeUSD
    previous24hVolume
  }
}
```

2024-05-28 06:43 UTC, gabrielmatei approved these changes

2024-05-28 08:23 UTC, cfaur09 approved these changes

2024-05-28 08:23 UTC, cfaur09 commented
Tested 🟢

2024-05-28 10:57 UTC, claudiulataretu requested changes

2024-05-28 10:57 UTC, claudiulataretu commented on src/modules/tokens/models/esdtToken.model.ts
> +    volumeUSD?: string;
don't rename this field, keep it as was before

2024-05-28 10:57 UTC, claudiulataretu commented on src/modules/tokens/services/token.setter.service.ts
> +    async setVolumeLast2D(
`setVolumeLast2Days`

2024-05-28 13:06 UTC, gabrielmatei approved these changes

2024-05-28 14:12 UTC, claudiulataretu submitted a review, later dismissed

2024-05-28 14:43 UTC, cfaur09 submitted a review, later dismissed

2024-05-29 07:34 UTC, cfaur09 approved these changes

2024-05-29 08:03 UTC, claudiulataretu approved these changes

2024-05-29 08:20 UTC, merged