[SERVICES-2348] Token trades count
multiversx/mx-exchange-service pull request #1356
Opened 2024-05-27 07:31 UTC by mad2sm0key

## Reasoning
- 
- 
- 
  
## Proposed Changes
- 
- 
- 

## How to test
- 
- 
-

2024-05-28 06:53 UTC, gabrielmatei submitted a review, later dismissed

2024-05-28 09:27 UTC, cfaur09 approved these changes

2024-05-28 14:43 UTC, cfaur09 submitted a review, later dismissed

2024-05-30 08:55 UTC, claudiulataretu requested changes

2024-05-30 12:22 UTC, mad2sm0key commented on src/services/elastic-search/services/es.logs.service.ts
> +        private readonly elasticService: ElasticService,
done

2024-06-05 13:42 UTC, gabrielmatei approved these changes

2024-06-05 13:53 UTC, cfaur09 approved these changes

2024-06-05 14:48 UTC, claudiulataretu approved these changes

2024-06-05 14:48 UTC, merged