[SERVICES-2485] Update caching strategy for tokens metadata
multiversx/mx-exchange-service pull request #1382
Opened 2024-07-01 06:09 UTC by mad2sm0key

## Reasoning
- currently the TTL for existing cached token metadata is simply extended on request. A refetch of the data is only performed if the value is not present in cache 
  
## Proposed Changes
- add method for maintaining token metadata in cache warmer
- remove logic that extends TTL for values present in cache

## How to test
```
query {
  filteredTokens(
    filters: { identifiers: ["WEGLD-a28c59"] }
    pagination: { first: 200 }
    sorting: { sortField: TRENDING_SCORE, sortOrder: DESC }
  ) {
    edges {
      cursor
      node {
        identifier
        volumeUSD24h
        price
        circulatingSupply
      }
    }
    pageInfo {
      startCursor
      endCursor
    }
    pageData {
      count
      limit
      offset
    }
  }
}
```

2024-07-01 11:08 UTC, claudiulataretu commented on src/modules/tokens/services/token.service.ts
> +        return await this.cachingService.getOrSet(
use `GetOrSet` decorator

2024-07-01 12:52 UTC, mad2sm0key commented on src/modules/tokens/services/token.service.ts
> +        return await this.cachingService.getOrSet(
renamed method and added decorator

2024-07-02 07:06 UTC, cfaur09 approved these changes

2024-07-02 08:55 UTC, claudiulataretu requested changes

2024-07-02 08:55 UTC, claudiulataretu commented on src/modules/tokens/services/token.service.ts
> +        remoteTtl: CacheTtlInfo.ContractState.remoteTtl,
CacheTtlInfo.Token.remoteTtl

2024-07-02 08:59 UTC, mad2sm0key commented on src/modules/tokens/services/token.service.ts
> +        remoteTtl: CacheTtlInfo.ContractState.remoteTtl,
fixed

2024-07-02 11:25 UTC, claudiulataretu approved these changes

2024-07-02 11:26 UTC, cfaur09 approved these changes

2024-07-02 11:52 UTC, merged