[SERVICES-2651] Add extra fields to staking model
multiversx/mx-exchange-service pull request #1505
Opened 2024-10-10 11:57 UTC by mad2sm0key

## Reasoning
- expose values for staking APR and rewards remaining days if not capped by max APR
  
## Proposed Changes
- add `aprIfUncapped` and `rewardsRemainingDaysIfUncapped` fields to Staking model 
- add field resolvers and compute methods
- small refactor to remove duplicate code

## How to test
```
query {
  filteredStakingFarms(filters: {}, pagination: { first: 200 }) {
    edges {
      node {
        address
        farmingToken {
          identifier
        }
        apr
        aprIfUncapped
        rewardsRemainingDays
        rewardsRemainingDaysIfUncapped
      }
    }
  }
}
```

2024-10-10 19:25 UTC, cfaur09 commented
Test done 🟢

2024-10-10 19:25 UTC, cfaur09 approved these changes

2024-10-11 11:36 UTC, claudiulataretu requested changes

2024-10-11 11:36 UTC, claudiulataretu commented on src/modules/staking/models/staking.model.ts
> +    aprIfUncapped: string;
rename into `aprUncapped`

2024-10-11 11:36 UTC, claudiulataretu commented on src/modules/staking/models/staking.model.ts
> +    rewardsRemainingDaysIfUncapped: number;
rename into `rewardsRemainingDaysUncapped`

2024-10-11 11:36 UTC, claudiulataretu commented on src/modules/staking/services/staking.compute.service.ts
> +    private async rewardsDepletedOrDisabled(
rename into `produceRewards` or `isProducingRewards`

2024-10-11 11:52 UTC, mad2sm0key commented on src/modules/staking/models/staking.model.ts
> +    aprIfUncapped: string;
done

2024-10-11 11:52 UTC, mad2sm0key commented on src/modules/staking/services/staking.compute.service.ts
> +    private async rewardsDepletedOrDisabled(
done

2024-10-11 11:54 UTC, claudiulataretu approved these changes

2024-10-11 11:56 UTC, gabrielmatei approved these changes

2024-10-11 11:58 UTC, merged