[SERVICES-2603] Refactor ES integration to use events index
multiversx/mx-exchange-service pull request #1506
Opened 2024-10-11 07:56 UTC by mad2sm0key

## Reasoning
- 
- 
- 
  
## Proposed Changes
- 
- 
- 

## How to test
- 
- 
-

2024-10-15 06:16 UTC, cfaur09 approved these changes

2025-01-10 14:40 UTC, claudiulataretu requested changes

2025-01-10 14:53 UTC, mad2sm0key commented on src/modules/governance/services/governance.compute.service.ts
> +        return await this.elasticEventsService.getGovernanceVotes(
done

2025-01-10 15:30 UTC, claudiulataretu approved these changes

2025-01-13 08:52 UTC, cfaur09 approved these changes

2025-01-13 08:52 UTC, merged