SERVICES-1379: compute undistributedBoostedRewards
multiversx/mx-exchange-service pull request #982
Opened 2023-03-03 13:50 UTC by dragos-rebegea

compute undistributedBoostedRewards including unclaimed rewards

## Reasoning
- 
- 
- 
  
## Proposed Changes
- 
- 
- 

## How to test
- 
- 
-

2023-07-10 11:02 UTC, claudiulataretu requested changes

2023-07-10 11:02 UTC, claudiulataretu commented on src/modules/farm/v2/services/farm.v2.compute.service.ts
> +            return new BigNumber(acc).plus(curr).integerValue().toFixed();
you can return BigNumber here

2023-07-10 12:10 UTC, dragos-rebegea commented on src/modules/farm/specs/farm.v2.compute.service.spec.ts
> +        // expect(mockFarmAbi.undistributedBoostedRewards).toHaveBeenCalled();
I let them for me for future reference to be implemented when it will be possible.

2023-07-10 12:45 UTC, claudiulataretu submitted a review, later dismissed

2023-07-13 08:59 UTC, claudiulataretu requested changes

2023-07-13 08:59 UTC, claudiulataretu commented on src/modules/farm/v2/services/farm.v2.getter.service.ts
remove empty file

2023-07-14 07:59 UTC, claudiulataretu approved these changes

2023-07-14 08:09 UTC, closed without merging